variable "rg_name" {}
variable "location" {}
variable "hub-vnet-name" {}
variable "app1-vnet-name" {}
variable "app2-vnet-name" {}
variable "hub-cidr" {}
variable "app1-cidr" {}
variable "app2-cidr" {}
variable "allowall" {}
variable "mgmtSubnetName" {}
variable "mgmtSubnet" {}
variable "untrustSubnetName" {}
variable "untrustSubnet" {}
variable "trustSubnetName" {}
variable "trustSubnet" {}
variable "app1SubnetName" {}
variable "app1Subnet" {}
variable "app2SubnetName" {}
variable "app2Subnet" {}
variable "instancetype" {}
variable "instanceSku" {}
variable "instanceVersion" {}
variable "customdatafw1" {}
variable "customdatafw2" {}
variable "adminUsername" {}
variable "adminPassword" {}
variable "bootstrap" {}
variable "www_script_path1" {}
variable "www_script_path2" {}
variable "bootstrap_sa1" {}
variable "sa_key1" {}
variable "file_share1" {}
variable "share_dir1" {}
variable "bootstrap_sa2" {}
variable "sa_key2" {}
variable "file_share2" {}
variable "share_dir2" {}